---
########################## dev
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/wechat?characterEncoding=UTF-8 
    username:  96db
    password:  Password@123456
    driverClassName: com.mysql.jdbc.Driver
  redis:
    host: 192.168.0.24
    port: 6379
    password: 19181716
    pool:
      max-active: 20
      max-wait: 1
      max-idle: 10
      min-idle: 1
    database: 15   
author: 
  ignoreUrls: /favicon.ico,/,/home,/error,/v2/api-docs,/v1/security/loginFail,/v1/security/loginSuccess,/login,/system/**,/swagger/**,/wx/**,/weChat/**
filePath: 
  fileRoot: e:/test
  imageRoot: e:/test
  articleSavePath: e:/test
  maxFileSize: 2
#微信配置
weChat:
  appId: wx8438d27cf8b599f0
  secret: 74585fda7e0c6007a0f74c77cc0e3c84
  #服务域名
  appDns: 192.168.0.125:5660
  appToke: vdcsm
  #缓存微信全局token 和Ticket的方式
  cacheTokenType: redis
appDns: http://192.168.0.125:5660