---
########################## dev
server:
  port: 7770
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/wechat_open_platform?characterEncoding=UTF-8
    username:  96test
    password:  Password@123456
    driverClassName: com.mysql.jdbc.Driver
        #redis
  redis:
    host: 192.168.0.24
    port: 6379
    password: 19181716
    pool:
      max-active: 20
      max-wait: 1
      max-idle: 10
      min-idle: 1
    database: 15
    
author:
  ignoreUrls: /favicon.ico,/,/home,/error,/v2/api-docs,/v1/security/loginFail,/v1/security/loginSuccess,/login,/swagger/**,/system/**,/module/**,/wx/**,/weChat/**,/v1/competence/findCompetencePermissionByUrl
  ignoreMethodCheckRoles: ADMIN
#微信配置
weChat:
  appId: wx9e3c29c071d9a1e2
  secret: 6403ce09cceeb0978dc5d5a06f067664
  #服务域名
  oAuthCallbackDomain: cooty.iask.in:11944
  appToke: vdnhbeer
  #缓存微信全局token 和Ticket的方式
  cacheTokenType: mysql
  #邮件里的MCHID
  mch_id: 1487250992
  #在微信商户平台pay.weixin.com里自己生成的那个key
  partner_key: 111111111111111
  #支付完成后微信发给该链接信息，可以判断会员是否支付成功，改变订单状态等。
  notify_url: http://nh.91-ec.com/wx/rtcode
  bind_telephone_template: tYqesZwueNcHVzLRu_FZ6aTGRsqGZDBrNcldSXW3pxM
  system_template: Gpr-qySi1DKGFY3NwhIOyn1TaKujk7bhzO01nkS9tbA
  unbind_gateway_template: 7qzjreCGHqCkAlQ7I3N7XgNA3d4oqKni7hr1QV947Is
  bind_gateway_template: eswrHrvRlpBvfBGq2uEEn0zY0EXFTk7cKIiEpxesIcI
  unbind_socket_template: np6gxsZNLI8jGumLcfA4o9wLzxAdojYoKOa1-yab9RU
  bind_updatePhone_template: 12121141
  electric_statistics: 0iRA0US1TUj1FqUewk4VgAgG_yF-FIDYeDnJGEdnABs  
appDns: http://cooty.iask.in:11944


  
  